repos:
  - repo: local
    hooks:
      - id: validate-frontmatter
        name: Validate frontmatter
        entry: python3 -m scripts.pre_commit_frontmatter.validate
        files: ^notes/.*\.md$
        language: python
        stages: [pre-commit]
        additional_dependencies:
          - pyyaml
