repos:
  - repo: local
    hooks:
      - id: validate-frontmatter
        name: Validate frontmatter
        entry: python3 scripts/pre_commit_frontmatter/validate.py
        files: ^notes/.*\.md$
        language: system
        stages: [pre-commit]
        additional_dependencies: []
