repos:
  - repo: local
    hooks:
      - id: validate-frontmatter
        name: Validate frontmatter
        entry: scripts/pre_commit_frontmatter/entrypoint.py
        files: ^notes/.*\.md$
        language: python
        stages: [pre-commit]
        additional_dependencies:
          - pyyaml==6.0.3
